# --- Experiment Setup ---
experiment_name: "Overfitting-Experiment2" #"Wave-Equation-BCSNN" #"Wave-Equation"
run_name: "BCSNN"
mlflow_tracking_uri: "https://63d839c6b182.ngrok-free.app" #"file:./mlruns"

# --- Problem Definition ---
problem:
  name: "HeatEquationProblem"
  L: 1.0
  T: 1.0
  alpha: 0.0005 # Thermal diffusivity for heat equation
  ic_type: "sum_sine"
  ic_params:
    # A simple initial condition for testing
    sum_sine_components: 
      - [5.0, 9.4247]
  ic_bcs:         # Which initial conditions and boundary conditions to use
    ic: false
    bc: false

# --- Model Architecture ---
model:
  name: "BCSNN"  # Use the standard PINN (MLP) model
  mlp:
    hidden_dim: 30
    num_layers: 3
    activation: "tanh"
  output_transform: false
  n_freq_fixed: 20
  n_freq_learnable: 0
  k_init_bounds: [-1.0, 150.0]

# --- Training ---
trainer:
  name: "StandardTrainer"
  # loss weights for [PDE, BC, IC_u, IC_ut]
  loss_weights: [1.0]
  optimizer: "Adam"
  learning_rate: 0.001
  iterations: 10000
  use_lbfgs: true
  lbfgs_maxiter: 10000
  save_model: false

# --- Data & Sampling ---
data:
  num_domain: 500
  num_boundary: 0
  num_initial: 0
  num_test: 500

# --- Execution ---
execution:
  device: "gpu"
  # NEW: Optional path to a pre-trained model run
  # If specified, training will be skipped.
  # format: "mlruns/<experiment_id>/<run_id>/artifacts/model"
  load_model_path: null # or e.g., "mlruns/1/d3a4b.../artifacts/model"