experiment_name: "Schrodinger-NLS-PINN"
run_name: "StandardPINN"
mlflow_tracking_uri: "file:./mlruns"

problem:
  name: "SchrodingerEquationProblem"
  ground_truth_path: "dataset/NLS.mat"

model:
  name: "StandardPINN"
  output_dim: 2  # CRITICAL: Predicts u and v
  mlp:
    hidden_dim: 100
    num_layers: 4
    activation: "tanh"
  output_transform: false

trainer:
  name: "StandardTrainer"
  # 2 PDE + 2 IC + 4 BC = 8 loss terms. Start with equal weights.
  loss_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  learning_rate: 0.001
  iterations: 20000
  use_lbfgs: true
  lbfgs_maxiter: 20000
  save_model: false

data:
  num_domain: 10000
  num_boundary: 200
  num_initial: 200

execution:
  device: "gpu"