# --- Experiment Setup ---
experiment_name: "Wave-Equation-VarBCSNN-relu" #"Wave-Equation"
run_name: "VarBCSNN"
mlflow_tracking_uri: "file:./mlruns"

# --- Problem Definition ---
problem:
  name: "WaveEquationProblem"  # Use the wave equation problem class
  L: 1.0
  T: 1.0
  c_squared: 100.0  # Physical parameter for the wave equation
  ic_params:
    mode: 2       # Initial standing wave mode
    delta: 1.0   # Initial amplitude
    multi: true
  ic_bcs:         # Which initial conditions and boundary conditions to use
    ic: false
    bc: false
    ic_ut: false

# --- Model Architecture ---
model:
  name: "VarBCSNN"  # Use the standard PINN (MLP) model
  mlp:
    hidden_dim: 200
    num_layers: 3
    activation: "tanh"
  output_transform: false
  n_freq_fixed: 10
  n_freq_learnable: 10
  k_init_bounds: [-1.0, 20.0]

# --- Training ---
trainer:
  name: "StandardTrainer"
  # loss weights for [PDE, BC, IC_u, IC_ut]
  loss_weights: [1.0]
  optimizer: "Adam"
  learning_rate: 0.001
  iterations: 40000
  use_lbfgs: false
  lbfgs_maxiter: 20000
  save_model: false

# --- Data & Sampling ---
data:
  num_domain: 360
  num_boundary: 0
  num_initial: 0
  num_test: 360

# --- Execution ---
execution:
  device: "gpu"