# --- Experiment Setup ---
experiment_name: "Multi-scale wave" #"Wave-Equation"
run_name: "SNN"
mlflow_tracking_uri: "file:./mlruns"

# --- Problem Definition ---
problem:
  name: "WaveEquationProblem"  # Use the wave equation problem class
  L: 1.0
  T: 1.0
  c_squared: 100.0  # Physical parameter for the wave equation
  ic_params:
    mode: 2       # Initial standing wave mode
    delta: 1.0   # Initial amplitude
    multi: true
  ic_bcs:         # Which initial conditions and boundary conditions to use
    ic: true
    bc: true
    ic_ut: true

# --- Model Architecture ---
model:
  name: "SpectralNN"  # Use the standard PINN (MLP) model
  mlp:
    hidden_dim: 200
    num_layers: 3
    activation: "tanh"
  output_transform: false
  n_freq_k_learnable: 10
  k_init_bounds: [-1.0, 20.0]

# --- Training ---
trainer:
  name: "SpectralTrainer"
  # loss weights for [PDE, BC, IC_u, IC_ut]
  loss_weights: [1.0e-2, 1.0e+2, 1.0e+3, 1.0e-3]
  optimizer: "Adam"
  learning_rate: 0.001
  iterations: 40000
  use_lbfgs: false
  lbfgs_maxiter: 10000
  save_model: false

# --- Data & Sampling ---
data:
  num_domain: 360
  num_boundary: 360
  num_initial: 360
  num_test: 360

# --- Execution ---
execution:
  device: "gpu"