# --- Experiment Setup ---
experiment_name: "Wave-Equation-PINN" #"Wave-Equation"
run_name: "Std_PINN_res"
mlflow_tracking_uri: "file:./mlruns"

# --- Problem Definition ---
problem:
  name: "WaveEquationProblem"  # Use the wave equation problem class
  L: 1.0
  T: 1.0
  c_squared: 2.0  # Physical parameter for the wave equation
  ic_params:
    mode: 4       # Initial standing wave mode
    delta: 10.0   # Initial amplitude
  ic_bcs:         # Which initial conditions and boundary conditions to use
    ic: true
    bc: true
    ic_ut: true

# --- Model Architecture ---
model:
  name: "StandardPINN"  # Use the standard PINN (MLP) model
  mlp:
    hidden_dim: 30
    num_layers: 3
    activation: "tanh"
  output_transform: false

# --- Training ---
trainer:
  name: "StandardTrainer"
  # loss weights for [PDE, BC, IC_u, IC_ut]
  loss_weights: [1.0e-2, 1.0, 1.0e+3, 1.0e-3]
  optimizer: "Adam"
  learning_rate: 0.001
  iterations: 10000
  use_lbfgs: true
  lbfgs_maxiter: 10000

# --- Data & Sampling ---
data:
  num_domain: 500
  num_boundary: 100
  num_initial: 100
  num_test: 500

# --- Execution ---
execution:
  device: "gpu"